import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useDocking } from '@/context/DockingContext';
import styles from './DockZones.module.scss';
export const DockZones = () => {
    const { state } = useDocking();
    if (!state.showDockZones) {
        return null;
    }
    return (_jsxs("div", { className: styles.dockZones, children: [_jsx("div", { className: `${styles.dockZone} ${styles.topLeft}`, "data-zone": "top-left", children: _jsx("div", { className: styles.zoneIndicator, children: _jsx("span", { children: "Top Left" }) }) }), _jsx("div", { className: `${styles.dockZone} ${styles.topRight}`, "data-zone": "top-right", children: _jsx("div", { className: styles.zoneIndicator, children: _jsx("span", { children: "Top Right" }) }) }), _jsx("div", { className: `${styles.dockZone} ${styles.bottomLeft}`, "data-zone": "bottom-left", children: _jsx("div", { className: styles.zoneIndicator, children: _jsx("span", { children: "Bottom Left" }) }) }), _jsx("div", { className: `${styles.dockZone} ${styles.bottomRight}`, "data-zone": "bottom-right", children: _jsx("div", { className: styles.zoneIndicator, children: _jsx("span", { children: "Bottom Right" }) }) }), _jsx("div", { className: `${styles.dockZone} ${styles.topCenter}`, "data-zone": "top-center", children: _jsx("div", { className: styles.zoneIndicator, children: _jsx("span", { children: "Top" }) }) }), _jsx("div", { className: `${styles.dockZone} ${styles.bottomCenter}`, "data-zone": "bottom-center", children: _jsx("div", { className: styles.zoneIndicator, children: _jsx("span", { children: "Bottom" }) }) }), _jsx("div", { className: `${styles.dockZone} ${styles.leftCenter}`, "data-zone": "left-center", children: _jsx("div", { className: styles.zoneIndicator, children: _jsx("span", { children: "Left" }) }) }), _jsx("div", { className: `${styles.dockZone} ${styles.rightCenter}`, "data-zone": "right-center", children: _jsx("div", { className: styles.zoneIndicator, children: _jsx("span", { children: "Right" }) }) })] }));
};
